#!/usr/bin/env python
import argparse

"""
Aurgument Parser Class
This may need to be modified for each individual type.
"""
class get_args():
    def __init__(self):
        self.args = self.getargs()

    def __get_app_version__(self):
        from dmrutils import DMRUtils
        TEMP = DMRUtils()
        return TEMP.__version__()
            
    def getargs(self):
        version = self.__get_app_version__()
        parser = argparse.ArgumentParser(
            description = 'Convert RADIOID.NET user.csv file to ' + \
                          'Anytone AT-8x8 UV Format.',
            epilog = 'This class is normally inherited by another '+ \
                     'for a specific radio or family of radios.')
        parser.add_argument('-v', '--version', action='version', version = version)
        parser.add_argument("-i", "--inputpath", default=None,
            help="Specifies the path to the DMR ID file in .csv format.")
        return parser.parse_args()


"""
Main program - run stand-alone if not included as part of a larger application
"""
if __name__ == '__main__':
    args = get_args()
    if (args.args.inputpath):
       from dmrutils import DMRUtils       
       app = DMRUtils(args.args.inputpath.strip())
    else:
       from gui_dmrutils import guiDMRUtils
       app = guiDMRUtils() 
